version: '3'
services:
  db: 
    hostname: db
    build:
      context: .
      dockerfile: ./db.Dockerfile 
    # env_file:
    #   - ./.env
    volumes:
      - ./db/mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql 
  quieingdb: 
    hostname: quieingdb
    build:
      context: .
      dockerfile: ./quieingdb.Dockerfile 
    env_file:
      - ./.env
    volumes:
      - ./db/mysql/quieingdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    depends_on: 
      - db
  userapi:
    hostname: userapi
    build:
      context: .
      dockerfile: ./twitter_api.Dockerfile
    volumes:
      - ./source/base:/source/base
      - ./source/base:/source/user
    user: root
    # environment:
    env_file:
      - ./.env
  tweetapi:
    hostname: tweetapi
    build:
      context: .
      dockerfile: ./twitter_api.Dockerfile
    volumes:
      - ./source/base:/source/base
      - ./source/base:/source/tweet
    user: root
    # environment:
    env_file:
      - ./.env


